apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: m4-demo-5
  name: nodejs-sample
  namespace: alexeykazakov
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-sample
    weight: 100
status: {}
